name: Deploy DAGs
on:
  workflow_run:
    workflows: 
      - Validation
    types: 
      - completed
    branches: 
      - main
  pull_request:
    types:
      - closed
jobs:
  Deployment:
    strategy:
      matrix:
        deploy-env: [dev] # [dev, test, prod]
    uses: ./.github/workflows/deployment.yml
    with:
      deploy-env: ${{ matrix.deploy-env }}
      region: 'us-east-1'
      dest-s3-bucket-path: ${{ matrix.deploy-env }}
    secrets: inherit