name: Deploy DAGs
on:
  workflow_run:
    workflows: 
      - Validation
    types: 
      - completed
    branches: 
      - main
  # pull_request:
  #   types:
  #     - closed
jobs:
  Deployment:
    strategy:
      matrix:
        stage: [dev, test, prod]
      fail-fast: true
      max-parallel: 1
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/deployment.yml
    with:
      stage: ${{ matrix.stage }}
      region: 'us-east-1'
      dest-s3-bucket-path: ${{ matrix.stage }}
    secrets: inherit