name: Validate and Deploy DAGs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  Validation:
    uses: ./.github/workflows/test_dags.yml
  Deployment:
    needs:
      - Validation
    strategy:
      matrix:
        stage: [dev, test, prod]
      fail-fast: true
      max-parallel: 1
    uses: ./.github/workflows/deployment.yml
    with:
      stage: ${{ matrix.stage }}
      region: 'us-east-1'
      dest-s3-bucket-path: ${{ matrix.stage }}
    secrets: inherit