name: Validate and Deploy DAGs
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  Validation:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/validate.yml
  Deployment:
    needs:
      - Validation
    strategy:
      matrix:
        stage: [dev, test, prod]
      fail-fast: true
      max-parallel: 1
    uses: ./.github/workflows/deploy.yml
    with:
      stage: ${{ matrix.stage }}
      region: 'us-east-1'
      dest-s3-bucket-path: ${{ matrix.stage }}
    secrets: inherit