name: Validation
on:
  workflow_call:
  push:
    paths:
      - 'dags/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'dags/**'
    types:
      - opened
      - edited

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: testing workflow
        shell: bash
        run: echo 'hello'
      - name: Lint DAGs with Flake8
        uses: phaelin/dag-validation-action@main
        with:
          flake8: true
          dagsdir: 'dags'
      - name: Check code compliance with Black
        uses: phaelin/dag-validation-action@main
        with:
          black: true
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Test DAGs with PyTest
        uses: phaelin/dag-validation-action@main
        with:
          pytest: true